name: iabtcf_consent_info_platform_interface
description: Platform interface for the iabtcf_consent_info plugin.
version: 1.0.0
repository: https://github.com/blaugold/iabtcf_consent_info
issue_tracker: https://github.com/blaugold/iabtcf_consent_info/issues

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  plugin_platform_interface: ^1.1.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
